# Generated by Django 3.0.7 on 2020-06-08 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('upc', models.CharField(max_length=12)),
                ('part_number', models.CharField(max_length=10)),
                ('image_url', models.CharField(max_length=100)),
            ],
        ),
    ]
