# Generated by Django 3.0.7 on 2020-06-08 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workstation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='image_url',
            field=models.CharField(max_length=500),
        ),
    ]
