# Generated by Django 3.0.7 on 2020-06-16 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workstation', '0003_unit_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='details',
            field=models.TextField(max_length=9000, null=True),
        ),
    ]
