# Generated by Django 3.0.7 on 2020-10-23 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workstation', '0005_auto_20200618_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='category',
            field=models.CharField(blank=True, choices=[('CB', 'Combo Keyboards and Mouses'), ('KB', 'Keyboards'), ('MS', 'Mouses'), ('SH', 'Speakers and Headsets'), ('GD', 'Gamepads'), ('TH', 'Others')], max_length=30, null=True),
        ),
    ]
