# Generated by Django 3.0.7 on 2020-10-23 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workstation', '0006_unit_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='category',
            field=models.CharField(blank=True, choices=[('Combo Keyboards and Mouses', 'Combo Keyboards and Mouses'), ('KB', 'Keyboards'), ('MS', 'Mouses'), ('SH', 'Speakers and Headsets'), ('GD', 'Gamepads'), ('TH', 'Others')], max_length=30, null=True),
        ),
    ]
