# Generated by Django 3.0.7 on 2020-10-23 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workstation', '0007_auto_20201023_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='category',
            field=models.CharField(blank=True, choices=[('Combo Keyboards and Mouses', 'Combo Keyboards and Mouses'), ('Keyboards', 'Keyboards'), ('Mouses', 'Mouses'), ('Speakers and Headsets', 'Speakers and Headsets'), ('Gamepads', 'Gamepads'), ('Others', 'Others')], max_length=30, null=True),
        ),
    ]
