# Generated by Django 3.0.7 on 2020-10-23 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workstation', '0010_auto_20201023_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workstation.Category'),
        ),
    ]
