# Generated by Django 3.0.7 on 2020-06-09 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workstation', '0002_auto_20200608_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_printed', models.DateTimeField(auto_now=True)),
                ('copies_printed', models.CharField(max_length=2)),
                ('label_type', models.CharField(choices=[('EBL', 'ExtraBoxLabel'), ('BLL', 'BoxLabel'), ('LUL', 'LogitechUnitLabel')], max_length=3)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workstation.Unit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
