# Generated by Django 3.0.7 on 2020-10-26 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workstation', '0012_auto_20201026_1027'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_title', models.CharField(max_length=300, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScrapRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('scrap_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('scrap_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workstation.Unit')),
            ],
        ),
        migrations.CreateModel(
            name='ScrapRecordToQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(default=None, max_length=50, unique=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrapmanager.Questions')),
                ('scrap_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrapmanager.ScrapRecord')),
            ],
        ),
        migrations.AddField(
            model_name='questions',
            name='question_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrapmanager.QuestionType'),
        ),
        migrations.CreateModel(
            name='CategoryQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workstation.Category')),
                ('questions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrapmanager.Questions')),
            ],
        ),
    ]
