# Generated by Django 3.0.7 on 2020-10-27 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapmanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scraprecordtoquestion',
            name='answer',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
