# Generated by Django 3.0.7 on 2020-10-28 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapmanager', '0002_auto_20201027_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraprecord',
            name='location',
            field=models.CharField(default='Table', max_length=20),
        ),
    ]
