# Generated by Django 3.0.7 on 2020-06-08 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='is_manager',
            new_name='is_staff',
        ),
    ]
